// Generated by CoffeeScript 2.6.1
(function() {
  var config, logger, socketWrapper;

  config = require('./config');

  logger = require('./logger');

  socketWrapper = require('./socketWrapper');

  // catch errors
  process.on('uncaughtException', function(err) {
    return logger.log(logger.logLevelEmergency, 'uncaughtException', err);
  });

  // read config
  config.get().then(function(configJson) {
    // logger
    logger.logLevel = configJson.logLevel;
    socketWrapper.logger = logger;
    // connect to the socket-port and listen it
    socketWrapper.secretKey = configJson.secretKey;
    return socketWrapper.init(configJson.port);
  }).done();

}).call(this);

//# sourceMappingURL=index.js.map
