// Generated by CoffeeScript 2.6.1
(function() {
  // work with socket.io http://socket.io/ https://github.com/socketio/socket.io/tree/master/docs

  // socket.emit('message', 'this is a test') - send to sender
  // socket.broadcast.emit('message', 'this is a test') - send to everyone except the sender
  // io.sockets.emit('message', 'this is a test') - send to everyone, including the sender

  // socket.broadcast.to('game').emit('message', 'cool game') - send to everyone in the channel except the sender
  // io.sockets.in('game').emit('message', 'cool game') - send to everyone in the channel, including the sender

  // io.sockets.socket(socketid).emit('message', 'for your eyes only') - send to socketid
  var crypto, express, fs, io, options, self, server;

  fs = require('fs');

  express = require('express')();

  if (fs.existsSync('ssl/cert.key') && fs.existsSync('ssl/cert.crt')) {
    // https
    options = {
      key: fs.readFileSync('ssl/cert.key'),
      cert: fs.readFileSync('ssl/cert.crt')
    };
    server = require('https').Server(options, express);
  } else {
    // http
    server = require('http').Server(express);
  }

  io = require('socket.io').listen(server);

  crypto = require('crypto');

  module.exports = self = {
    // logger
    logger: null,
    // signature password
    secretKey: '',
    // socket to user: socketId => handshakeData
    socketsData: {},
    // handshake (check signature)
    // check GET-params: md5(param1=paramValue1param2=paramValue2secretKey) = sig
    handshake: function(socket) {
      var handshakeData, hash, isOk, j, len, paramName, required, sig, strToHash;
      required = ['user', 'userId', 'sig'];
      handshakeData = socket.request._query;
      strToHash = '';
      for (j = 0, len = required.length; j < len; j++) {
        paramName = required[j];
        if (!handshakeData[paramName]) {
          self.logger.log(self.logger.logLevelError, 'ParamName is not set ' + paramName);
          return false;
        }
        if (paramName === 'sig') {
          continue;
        }
        strToHash += paramName + '=' + handshakeData[paramName];
      }
      strToHash += self.secretKey;
      sig = handshakeData['sig'];
      hash = crypto.createHash('md5').update(strToHash).digest('hex');
      isOk = hash === sig;
      if (isOk) {
        self.logger.log(self.logger.logLevelDebug, {
          str: strToHash,
          hash: hash,
          sig: sig
        });
      } else {
        self.logger.log(self.logger.logLevelInfo, {
          str: strToHash,
          hash: hash,
          sig: sig
        });
      }
      return isOk;
    },
    // remember socket and user
    setUserBySocket: function(socket, data) {
      if (data) {
        return self.socketsData[socket.id] = data;
      } else {
        return delete self.socketsData[socket.id];
      }
    },
    // get user by socket
    getUserBySocket: function(socket) {
      var socketId;
      socketId = socket.id.toString();
      return self.socketsData[socketId];
    },
    // get sockets by user
    getSocketsByUser: function(user) {
      var ref, socketData, socketId, sockets;
      sockets = [];
      ref = self.socketsData;
      for (socketId in ref) {
        socketData = ref[socketId];
        if (socketData['user'].toString() === user.toString()) {
          sockets.push(io.sockets.sockets[socketId]);
        }
      }
      return sockets;
    },
    // get sockets by userId
    getSocketsByUserId: function(userId) {
      var ref, socketData, socketId, sockets;
      sockets = [];
      ref = self.socketsData;
      for (socketId in ref) {
        socketData = ref[socketId];
        if (socketData['userId'].toString() === userId.toString()) {
          sockets.push(io.sockets.sockets[socketId]);
        }
      }
      return sockets;
    },
    // init
    init: function(port) {
      // listen a port
      server.listen(port, function() {
        // after connect
        return self.logger.log(self.logger.logLevelNotice, 'Listening on port ' + port);
      });
      express.get('/', function(request, response) {
        var statString;
        // root request
        // return statistic
        statString = JSON.stringify({
          clientsCount: io.engine.clientsCount,
          //        clients: Object.keys(io.engine.clients),
          socketsData: self.socketsData
        });
        response.writeHead(200, {
          'Content-Type': 'application/json'
        });
        response.write(statString);
        return response.end();
      });
      // handshake (check signature)
      io.use(function(socket, next) {
        var handshakeData;
        handshakeData = socket.request._query;
        if (self.handshake(socket)) {
          self.logger.log(self.logger.logLevelDebug, 'Handshake ' + handshakeData['user'] + ' ' + socket.id);
          self.setUserBySocket(socket, handshakeData); // remember socket and user
          return next();
        } else {
          self.logger.log(self.logger.logLevelError, 'Handshake error ' + socket.id, handshakeData);
          return next(new Error('not authorized')); // wrong request
        }
      });
      return io.on('connection', function(socket) {
        var user, userId;
        // on connect new user
        user = self.getUserBySocket(socket)['user'];
        userId = self.getUserBySocket(socket)['userId'];
        self.logger.log(self.logger.logLevelInfo, 'Connected ' + user + ' ' + socket.id);
        socket.on('message', function(params) {
          var i, tmpSocket, tmpSockets;
          // on receive a message from a user
          if (params instanceof String) {
            // convert a string to an object
            params = {
              message: params
            };
          }
          params['userFrom'] = user;
          params['userIdFrom'] = userId;
          params['socketIdFrom'] = socket.id;
          if (params['userTo'] || params['userIdTo']) {
            // send to the exact user
            if (params['userIdTo']) {
              tmpSockets = self.getSocketsByUserId(params['userIdTo']);
            } else {
              tmpSockets = self.getSocketsByUser(params['userTo']);
            }
            if (tmpSockets.length === 0) {
              self.logger.log(self.logger.logLevelNotice, 'Message. User not found', params);
              return;
            }
            self.logger.log(self.logger.logLevelInfo, 'Message.user', params);
            for (i in tmpSockets) {
              tmpSocket = tmpSockets[i];
              tmpSocket.emit('message', params);
            }
            return;
          }
          // send to everybody
          self.logger.log(self.logger.logLevelInfo, 'Message', params);
          return io.emit('message', params);
        });
        return socket.on('disconnect', function() {
          // on disconnect
          self.logger.log(self.logger.logLevelInfo, 'Disconnected ' + user + ' ' + socket.id);
          return self.setUserBySocket(socket, null); // сбросить данные юзера для сокета
        });
      });
    }
  };

}).call(this);

//# sourceMappingURL=socketWrapper.js.map
