version: '3.7'

services:
  nginx:
    ports:
      - ${NGINX_PORT:-8080}:80

  php:
    extra_hosts:
      - host.docker.internal:host-gateway # Magic for xDebug in Ubuntu. It's not necessary for Mac or Windows
    volumes:
      - ../src_php/:/var/www/ # PHP src
      - ./php-xdebug.ini:/usr/local/etc/php/conf.d/php-xdebug.ini # xDebug

  adminer:
    ports:
      - ${ADMINER_PORT:-8081}:8080
