// Generated by CoffeeScript 2.6.1
(function() {
  // read config
  var Q, fs, self;

  fs = require('fs');

  Q = require('q'); // @link https://github.com/kriskowal/q/

  module.exports = self = {
    dataPromise: null, // cache
    get: function(paramName) {
      var configFileName, readFile;
      // read a config-file if not in cache
      if (!self.dataPromise) {
        configFileName = process.argv[2] != null ? process.argv[2] : './config.json';
        readFile = Q.denodeify(fs.readFile);
        self.dataPromise = readFile(configFileName).then(function(data) {
          return JSON.parse(data);
        });
      }
      // get data from cache
      return self.dataPromise.then(function(data) {
        if (paramName) {
          return data[paramName];
        } else {
          return data; // all data
        }
      });
    }
  };

}).call(this);

//# sourceMappingURL=config.js.map
