// Generated by CoffeeScript 2.6.1
(function() {
  // write logs
  var self;

  module.exports = self = {
    // minimal level for logging
    logLevel: 250,
    // @link https://github.com/Seldaek/monolog/blob/master/src/Monolog/Logger.php
    logLevelDebug: 100,
    logLevelInfo: 200,
    logLevelNotice: 250,
    logLevelWarning: 300,
    logLevelError: 400,
    logLevelCritical: 500,
    logLevelAlert: 550,
    logLevelEmergency: 600,
    log: function(logLevel) {
      if (self.logLevel && logLevel >= self.logLevel) {
        if (logLevel >= self.logLevelWarning) {
          return console.error(Date(), arguments);
        } else {
          return console.log(Date(), arguments);
        }
      }
    }
  };

}).call(this);

//# sourceMappingURL=logger.js.map
