input {
  beats {
    port => 5044
    host => "0.0.0.0"
  }
}

filter {
  mutate {
    gsub => [
      "uri",     "[\\?#].*$", "",
      "referer", "[\\?#].*$", ""
    ]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    pipeline => "geoip_user_agent"
    index  => "nginx-access-%{+yyyy.MM.dd}"
  }
}