name: CI/CD. Build Docker image, tag it "latest" and deploy to Portainer LATEST

on:
  push:
    branches:
      - master
    paths:
      - .github/workflow/**
      - php/mvc/**

jobs:
  # Build
  build-latest:
    uses: boriskorobkov/code-example/.github/workflows/_build.yml@master
    with:
      APP_PATH: php/mvc/
      DOCKERHUB_REPO: boriskorobkov/code-example
    secrets:
      DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  # Deploy
  deploy-latest:
    uses: boriskorobkov/code-example/.github/workflows/_deploy.yml@master
    with:
      PORTAINER_STACK: boriskorobkov/code-example-latest
    secrets:
      PORTAINER_HOST: ${{ secrets.PORTAINER_HOST }}
      PORTAINER_USERNAME: ${{ secrets.PORTAINER_USERNAME }}
      PORTAINER_PASSWORD: ${{ secrets.PORTAINER_PASSWORD }}
      PORTAINER_SWARM_ID: ${{ secrets.PORTAINER_SWARM_ID }}
    needs: build-latest
