name: Build Docker image, tag it with a version and deploy to Portainer QAT

on:
  push:
    tags:
      - "qat/*" # For example: "qat/1.10.2"

jobs:
  # Build
  build-qat:
    uses: boriskorobkov/code-example/.github/workflows/_build.yml@master
    with:
      APP_PATH: php/mvc/
      DOCKERHUB_REPO: boriskorobkov/code-example
    secrets:
      DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  # Deploy
  deploy-qat:
    uses: boriskorobkov/code-example/.github/workflows/_deploy.yml@master
    with:
      PORTAINER_STACK: boriskorobkov/code-example-qat
    secrets:
      PORTAINER_HOST: ${{ secrets.PORTAINER_HOST }}
      PORTAINER_USERNAME: ${{ secrets.PORTAINER_USERNAME }}
      PORTAINER_PASSWORD: ${{ secrets.PORTAINER_PASSWORD }}
      PORTAINER_SWARM_ID: ${{ secrets.PORTAINER_SWARM_ID }}
    needs: build-qat
