version: "3.7"

services:
  php:
    extra_hosts:
      - host.docker.internal:host-gateway # Magic for xDebug in Ubuntu. It's not necessary for Mac or Windows
    volumes:
      - ./php/php-xdebug.ini:/usr/local/etc/php/conf.d/php-xdebug.ini:ro # xDebug
