/root/volumes/nginx/logs/grafana_access.log {
    hourly
    rotate 0
    copytruncate
    missingok
    notifempty
}

/root/volumes/nginx/logs/error.log {
    daily
    rotate 7
    maxage 30
    compress
    copytruncate
    missingok
    notifempty
}
